deployment:
  tasks:
    - export SOURCE_PATH=~/repositories/rait-acm-compiled
    - export DEST_PATH=/home/raithosting/public_html

      # Remove everything in the destination except .git and README.md
    - rm -rf $DEST_PATH/*
    - rm -f $DEST_PATH/.* # Remove hidden files, but leave .git


      # Copy all files and directories from source to destination, excluding .git and README.md
    - cp -r $SOURCE_PATH/* $DEST_PATH/
    - cp -r $SOURCE_PATH/.[!.]* $DEST_PATH/ # Copy hidden files except .git and README.md
    - rm -rf $DEST_PATH/.git
    - rm -f $DEST_PATH/README.md
