deployment:
  tasks:
    - export SOURCE_PATH=~/repositories/rait-acm-compiled
    - export DEST_PATH=/home/raithosting/public_html

      # Remove the contents of the destination folder except .git and README.md
    - find $DEST_PATH -mindepth 1 -not -name '.git' -not -name 'README.md' -exec rm -rf {} +

      # Copy everything from source to destination, excluding .git and README.md
    - find $SOURCE_PATH -mindepth 1 -not -name '.git' -not -name 'README.md' -exec cp -r {} $DEST_PATH/ \;
